// core/analyze.js
const { matchesSubmitKeyword } = require('./submitDetector');
const { checkIfThisElementIsUnnecessary } = require('./unnecessaryDetector');
const { identifyFieldIntent, getMeaningfulContext } = require('./staticfieldDetector');
const { classifyInteractionType } = require('./elementClassifier');
const { getProfileValue } = require('./getFunctionCalling');
const { generateDynamicAnswer } = require('./aiService'); // <--- Import AI Service

async function analyzeData(data) {
	const children = data.Children || [];
	const parent = data.Parent;

	// 1. Submit Detection
	if (children.length === 1 && matchesSubmitKeyword(children[0])) {
		return {
			summary: 'Submit Application button detected.',
			action_suggestion: {
				command: 'CLICK',
				payload: {
					childIndex: 0,
					text: children[0].innerText
				}
			}
		};
	}

	// 2. Unnecessary Detection
	if (checkIfThisElementIsUnnecessary(parent, children)) {
		return { summary: 'Unnecessary element detected.', action_suggestion: null };
	}

	// 3. Classify Interaction Type
	const interactionType = classifyInteractionType(children);

	// 4. Identify Context
	const context = getMeaningfulContext(parent, children);
	const intent = identifyFieldIntent(context);

	let finalAction = null;

	// 5. Logic Engine
	if (intent.isStatic) {
		// --- STATIC FIELD LOGIC (Existing) ---
		const profileValue = getProfileValue(intent.field);

		if (interactionType === 'UPLOAD') {
			const inputIndex = children.findIndex(c => c.tag === 'input');
			finalAction = {
				command: "UPLOAD",
				payload: { value: profileValue, childIndex: inputIndex }
			};
		}
		else if (interactionType === 'TYPING' || interactionType === 'COMBOBOX') {
			const inputIndex = children.findIndex(c => c.tag === 'input' || c.tag === 'textarea');
			finalAction = {
				command: "TYPING",
				payload: { value: profileValue, childIndex: inputIndex }
			};
		}
		else if (interactionType === 'SELECTION_GROUP') {
			if (profileValue) {
				const targetIndex = children.findIndex(child => {
					const text = (child.innerText || '').toLowerCase().trim();
					const value = profileValue.toLowerCase().trim();
					return text === value;
				});

				if (targetIndex !== -1) {
					finalAction = {
						command: "CLICK",
						payload: { childIndex: targetIndex, text: children[targetIndex].innerText }
					};
				} else {
					finalAction = { command: "ERROR", reason: `Option '${profileValue}' not found.` };
				}
			} else {
				finalAction = { command: "ERROR", reason: `No profile value for '${intent.field}'` };
			}
		}
	} else {
		// --- DYNAMIC AI LOGIC (New) ---

		// If it's a text input or textarea but NOT a known static field (like Name/Email/CoverLetter)
		// It is likely a question like "Why do you want to work here?" or "Describe a challenge."
		if (interactionType === 'TYPING') {

			// 1. Call AI Service
			const aiResponse = await generateDynamicAnswer(context);

			// 2. Find the input element
			const inputIndex = children.findIndex(c => c.tag === 'input' || c.tag === 'textarea');

			finalAction = {
				command: "TYPING",
				payload: {
					value: aiResponse, // The text generated by OpenAI
					childIndex: inputIndex
				}
			};
		}
		else if (interactionType !== 'UNKNOWN') {
			// It's interactive (like a custom dropdown we don't recognize), but we can't type into it.
			// We flag it for manual review or return a generic message.
			return {
				summary: 'Complex dynamic field detected (Non-text).',
				question: context,
				action_suggestion: {
					command: "MANUAL_INTERVENTION",
					payload: { message: "Cannot automate this interaction type via AI yet." }
				}
			};
		}
	}

	return {
		summary: `Analyzed: ${intent.field || 'Dynamic Question'} (${interactionType})`,
		insights: {
			field: intent.field,
			interactionType: interactionType,
			context: context
		},
		action_suggestion: finalAction
	};
}

module.exports = { analyzeData };